### ISSUE TITLE
[BUG] Significant power consumption increase when plugin is running

### ISSUE THREAD

**Issue by Ferywir** [ruaan-deysel/ha-unraid-management-agent#8]
### **Description**

I installed the plugin and found it very feature-rich and well designed.  
However, I’m experiencing a **major increase in power consumption** when it is installed.

Under normal conditions, my Unraid server consumes around **30 W continuously**.  
After installing the plugin, power consumption rises to **45–50 W continuously**, representing an increase of approximately **50–60%**.

To further investigate, I also tested the behavior on the Home Assistant side:  
**whether the Home Assistant integration is enabled or disabled makes no difference — power consumption remains the same as long as the plugin is installed on Unraid.**

To confirm this behavior, I uninstalled the plugin and power usage immediately returned to normal.  
After reinstalling the plugin, the exact same behavior occurred again. The issue is therefore **fully reproducible**.

I’m wondering if this could be related to:
- a refresh or polling frequency that is too high;
- background tasks running too frequently;
- the CPU not properly entering low-power states while the plugin is installed.

If this aspect can be optimized, I’d be happy to reinstall the plugin, run additional tests, and share detailed results.

---

### **Environment**
- **Plugin version:** 2025.12.0
- **Unraid version:** 7.2.2

**Hardware**
- Motherboard: MSI PRO Z790-P WIFI
- CPU: Intel i5-14500
- RAM: 32 GB
- Storage:
  - 4× NVMe
  - 4× HDD

**System workload**
- Docker containers: ~25
- Virtual machines: 1 (Home Assistant)

---

### **Steps to reproduce**
1. Measure idle power consumption without the plugin (~30 W).
2. Install the plugin.
3. Enable or disable the Home Assistant integration (no impact observed).
4. Observe continuous power consumption of 45–50 W.
5. Uninstall the plugin → power consumption immediately returns to normal.

![Image](https://github.com/user-attachments/assets/1c5e621c-1d5a-41fb-9370-640f06f48c0b)

**Comment by ruaan-deysel** [comment]
Added configurable collection intervals to unraid management plugin to help reduce power consumption. These are the default settings.

<img width="1464" height="510" alt="Image" src="https://github.com/user-attachments/assets/a97b0ba1-ce2a-4038-99eb-52db1c64b2a1" />

I'll close this issue here as it belongs in the Unraid Management Agent plugin repo.

[https://github.com/ruaan-deysel/unraid-management-agent](url)

**Comment by ruaan-deysel** [comment]
@Ferywir This should be fixed now. You can fine tune the collection intervals.

**Comment by saladm2** [comment]
@ruaan-deysel  This is still an issue for me - while there are configurable collection intervals now in the plugin settings in unraid, the unraid uptime sensor in HA is still updating every 5 seconds. I disabled the sensor for now
